name: .NET Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [win]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: src/${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c release -o publish/${{ matrix.os }} --os ${{ matrix.os }} -p:Version=${{ steps.get-version.outputs.assembly-version }} --verbosity normal
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.1
      with:
        filename: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ steps.get-version.outputs.assembly-version }}.zip
        path: ${{ matrix.os }}/*
        directory: publish/
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: publish/*.zip
